# Generated by Django 2.0.3 on 2021-11-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_sex', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20, null=True)),
                ('student_addriess', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=20)),
            ],
        ),
    ]
